docs: add cairocffi/xcffib/cffi to deps
be402836b2b8a8bccd7d9477decce2151fb26dfc added a new dependency, which
broke our builds on RTD:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest/docs/sphinx_qtile.py", line 26, in <module>
    from libqtile import command_object, configurable, widget
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest/libqtile/widget/__init__.py", line 31, in <module>
    from .prompt import Prompt  # noqa: F401
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest/libqtile/widget/prompt.py", line 49, in <module>
    from libqtile.backend.x11 import xcbq
  File "/home/docs/checkouts/readthedocs.org/user_builds/qtile/checkouts/latest/libqtile/backend/x11/xcbq.py", line 52, in <module>
    import cairocffi.xcb
ModuleNotFoundError: No module named 'cairocffi.xcb'; 'cairocffi' is not a package

So let's add these new deps to our requirements.txt for building the docs.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>